// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktjrcdknewtliusorbcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0anJjZGtuZXd0bGl1c29yYmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjQ1NzQsImV4cCI6MjA3MzE0MDU3NH0._azPNgEv7sphuv9_kfEG8dAmAMPCgxPO__3sp_LGDRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});